/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Bessel */

#ifndef _Included_Bessel
#define _Included_Bessel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Bessel
 * Method:    bessely0
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_Bessel_bessely0
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
